from __future__ import annotations

from typing import Any, Callable, Iterable, Sequence


class _Component:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class Blocks:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> Blocks: ...
    def __exit__(self, exc_type: type[Any] | None, exc: BaseException | None, tb: Any | None) -> None: ...
    def launch(self, *args: Any, **kwargs: Any) -> Any: ...


class _ContextManager(_Component):
    def __enter__(self) -> _ContextManager: ...
    def __exit__(self, exc_type: type[Any] | None, exc: BaseException | None, tb: Any | None) -> None: ...


class Group(_ContextManager): ...
class Tab(_ContextManager): ...
class Row(_ContextManager): ...
class Column(_ContextManager): ...


class Markdown(_Component): ...


class Textbox(_Component):
    def click(self, fn: Callable[..., Any], inputs: Any | Sequence[Any] | None = None, outputs: Any | Sequence[Any] | None = None) -> None: ...


class Button(_Component):
    def click(self, fn: Callable[..., Any], inputs: Any | Sequence[Any] | None = None, outputs: Any | Sequence[Any] | None = None) -> None: ...


class Number(_Component):
    value: float | None


class Dropdown(_Component):
    choices: Iterable[Any]
